#!/bin/sh
##Script for copying the diffusion MRI nifti, bvecs, and bvals files into the correct folders for further processing
##Created by Lindsey Kitchell (IU graduate student 2017)

cp ./2017*MPRAGESAG*.nii.gz ./t1/
cp ./*PA*.nii.gz ./PA/
cp ./*AP*.nii.gz ./AP/
cp ./*MPRAGESAG*.nii.gz ../Anatomy/
cp ./*AP*.nii.gz ../diffusion/AP/
cp ./*PA*.nii.gz ../diffusion/PA/
cp ./bvals ../diffusion/
cp ./bvals ../diffusion/AP/
cp ./bvals ../diffusion/PA/
cp ./bvecs ../diffusion/
cp ./bvecs ../diffusion/AP/
cp ./bvecs ../diffusion/PA/

