#!/bin/bash

##Script for creating a white matter mask based on freesurfer output. This script will call a matlab function called
## fs_make_wm_mask. Written by Lindsey Kitchell (IU graduate student 2017)

#subj folder name
subj="subj_10024"
datadir="/N/dc2/scratch/kitchell/Cadaver_diffusion"

##load freesurfer
module load freesurfer

#setup freesurfer
export SUBJECTS_DIR=/N/u/kitchell/Karst/Applications/FS_subjects
source $FREESURFER_HOME/SetUpFreeSurfer.sh

cd $SUBJECTS_DIR/$subj/mri

#convert file types
mri_convert aparc+aseg.mgz aparc+aseg.nii.gz

cp $SUBJECTS_DIR/$subj/mri/aparc+aseg.nii.gz $datadir/$subj/diffusion_directory/Anatomy

#move to the data directory
cd $datadir

module load matlab

matlab -nodisplay -nojvm -r "fs_make_wm_mask('subj_10024')";exit;


