#!/bin/bash
#Script to automate the initial set up for each subject
#Written by Lindsey Kitchell (IU graduate student 2017)


subj="subj_10041"
datadir="/N/dc2/scratch/kitchell/Cadaver_diffusion"
 
mkdir ./$subj
cp ./make_directories ./$subj
cd ./$subj
./make_directories
cp $datadir/reorgDTI $datadir/$subj/diffusion_directory/bin/reorgDTI
cp $datadir/diffusion_clean $datadir/$subj/diffusion_directory/bin/diffusion_clean
cp $datadir/run_batch_clean.pbs $datadir/$subj/diffusion_directory/bin/run_batch_clean.pbs
cp $datadir/acq_params.txt $datadir/$subj/diffusion_directory/diffusion/acq_params.txt
cp  $datadir/copy_diff_images $datadir/$subj/diffusion_directory/RAW/
cp /N/u/kitchell/Karst/Downloads/$subj/* $datadir/$subj/diffusion_directory/RAW/
cd ./diffusion_directory/RAW/
unzip *MP*.zip
unzip *PA*.zip
unzip *AP*.zip

module load mricron
dcm2nii *dcm

mv *AP*.bval bvals
mv *AP*.bvec bvecs
./copy_diff_images
cd ..
mv ./diffusion/AP/*.nii.gz ./diffusion/AP/AP.nii.gz
mv ./diffusion/PA/*.nii.gz ./diffusion/PA/PA.nii.gz
