#!/bin/bash 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=45:00:00
#PBS -N 9946_fs
#PBS -o 9946_fs.output
#PBS -e 9946_fs.error
#PBS -m abe 
#PBS -M kitchell@indiana.edu 



##load freesurfer
module load freesurfer

#setup freesurfer
export SUBJECTS_DIR=/N/u/kitchell/Karst/Applications/FS_subjects
source $FREESURFER_HOME/SetUpFreeSurfer.sh

#set up subject
projdir1="/N/dc2/scratch/kitchell/Cadaver_diffusion"
subj="subj_9946"


#run recon-all
recon-all -i $projdir1/$subj/diffusion_directory/Anatomy/t1_acpc.nii.gz -subjid $subj -all